### ISSUE TITLE
aci set to false error

### ISSUE THREAD

**Issue by whottel** [UPHL-BioNGS/Cecret#225]
Hello,

I am running cecret version 3.8.20230830
 with the following command:
`/Shared/SHL-BUG/software/nextflow/nextflow run UPHL-BioNGS/Cecret -profile singularity,artic_V5_3_2 --reads . --freyja false --aci false --samtools_plot_ampliconstats false -c /Shared/SHL-BUG/singularity/Cecret/Cecret_custom.config`
I noticed with the most recent update that when aci is set to false the pipeline quickly fails, see attached log.
[Error.txt](https://github.com/UPHL-BioNGS/Cecret/files/12552828/Error.txt)

Thanks,
Wes

**Comment by erinyoung** [comment]
Oh no! This seems like a pretty major bug. Just a sec.

**Comment by erinyoung** [comment]
Thank you for bringing this to my attention!!! I have a fix https://github.com/UPHL-BioNGS/Cecret/pull/226 that should be released tomorrow morning.

**Comment by erinyoung** [comment]
It should be fixed now. Let me know if you run into anything else!

**Comment by erinyoung** [comment]
> Is there any difference between the assebmlies in these folders besides the header lines for the files?

Nope. That's the only difference. 

When I added artic for nanopore sequencing, I needed some way to get the results to make sense in the final summary file. Instead of putting together a million regex functions, I decided to simplify my life and change the header instead. I didn't want to cause too many issues with those who needed that header, though, so I kept that fasta as well. My apologies if the redundancy was confusing!
